language: php

sudo: false

branches:
  except:
  - l10n_2.4

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - cp .env.example .env
  - phpenv config-rm xdebug.ini

install: travis_retry composer install --no-interaction --no-suggest

script: vendor/bin/phpunit
